### PR TITLE
Grid Search variant

### LINKED ISSUE #10: Grid search variant
I think it would be useful to have a grid search optimizer in this package. But its implementation would probably be quite different from other ones (sklearn, ...). 

The requirements are:
 - The grid search has to stop after n_iter instead of searching the entire search space
 - The positions should not be precalculated at the beginning of the optimization (i have concerns about memory load).

### PR DESCRIPTION
**Pull request by tgdn**
Hi @SimonBlanke, we developed a solution to a grid search variant in this PR, let us know what you think and further improvements/changes.

This would fix #10.

Co-authors: @EdouardVilain-Git @tabeare @annabieber @MachineLearner75

### CODE REVIEW

**Comment by SimonBlanke** [comment]
Hello @tgdn,

this is some great work! I wouldn't have thought of this solution, but I really like it.

I created an animated visualization of the grid search:
grid_search_sphere_function

**Comment by SimonBlanke** [comment]
If it is not too much work I would suggest a parameter for this grid search that would make it even more useful:

An integer parameter, that determines the `step size` of the grid search in each iteration.

Example:
If this parameter is set to `3` the grid search wouldn't select the next position, but the one it would normally select after 3 iterations. This way we get a sparse grid after the first pass through the search space. After the first pass is done the grid search starts at the beginning and does a second pass with the same step size. And a third pass after that.

So if the `step size` is `n` the grid search would also need `n` passes through the search space to fully explore it.

I think this would be very useful to quickly explore the search space in a short amount of iterations if desired.
Does this explanation make sense to you?

**Comment by tgdn** [comment]
Thank you for your feedback @SimonBlanke , your explanation makes complete sense. I'll get back to you over the week-end or start of next week with updates!

**Review by SimonBlanke — CHANGES_REQUESTED** [review]
requested changes: add step-size parameter

**Comment by tgdn** [comment]
Hi @SimonBlanke, let us know if this is what you were thinking of.

**Comment by SimonBlanke** [comment]
Hello @tgdn, 

this is exactly what I was thinking of. This parameter makes the grid-search a great tool to explore the search space. 
I did some basic testing (in various search spaces) of your implementation and everything looks fine.

Thanks to you and your team @EdouardVilain-Git, @tabeare, @annabieber, @MachineLearner75 for this solution.
Here you have another visualization of your amazing work:

grid_search_sphere_function

**Review by SimonBlanke — APPROVED** [review]

**Pull request merged**
